compute_environment: LOCAL_MACHINE
debug: true
distributed_type: DEEPSPEED
deepspeed_config:
  deepspeed_config_file: /home/joseph/CHANGE_project/ds_config.json
num_processes: 1 # change number of GPUs here
num_machines: 1
machine_rank: 0

